backups:
    - PREFIX: Minecraft
      destination_dir: /root/backups/Minecraft
      zip_compression: true
      keep_window: 5

      source_directories:
          - /root/Minecraft Servers/A-Team/Server

      database_names:
          - Rimawification

      remote_backups:
          - host: RimawiHome
            path: /root/backups/Minecraft

    # - PREFIX: Databases
    #   destination_dir: /root/databases
    #   zip_compression: true
    #   keep_window: 5

    #   source_directories:
    #       - /root/backmeup

    #   database_names:
    #       - Rimawification

    #   remote_backups:
    #       - host: RimawiHome
    #         path: /root/dumy_backs/


    # - PREFIX: Alsaqifa
    #   destination_dir: ~/backups/Alsaqifa
    #   zip_compression: true
    #   keep_window: 5

    #   source_directories:
    #       - /var/www/html/wordpress/public_html

    #   database_names:
    #       - Alsaqifa_Wordpress

    #   remote_backups:
    #       - host: RimawiHome
    #         path: /root/backups/Alsaqifa
